USE SCHEMA NWT_DISTRIBUTOR;

MERGE INTO RAW_PRODUCT
USING PRODUCT_FRESH
ON RAW_PRODUCT.ProductID = PRODUCT_FRESH.ProductID
WHEN MATCHED THEN 
    UPDATE SET RAW_PRODUCT.UNITCOST = PRODUCT_FRESH.UNITCOST;