# This is a basic workflow to help you get started with Actions

name: Cleaning-CI/CD

on:
  push:
    branches:
      - main
    paths:
      - cleaning/**'

jobs:
  alter_database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Snowflake connection
      run: |
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      shell: bash

    - name: Execute SQL statements
      run: |
        # Use the <tool> command to execute SQL statements
        <tool> -c "ACCOUNT=${SNOWFLAKE_ACCOUNT} USER=${SNOWFLAKE_USER} PASSWORD=${SNOWFLAKE_PASSWORD} DATABASE=${SNOWFLAKE_DATABASE}" -f path/to/your/sql/script.sql
      shell: bash
